#!/usr/bin/env python3

from bs4 import BeautifulSoup
import sys
import urllib.request


def main():
	repo = get_repo_from_arguments()
	for i in range(1, 100):    # 100 is just an arbitrary limit...
		url = "https://github.com/{}/stargazers?page={}".format(repo, i)
		html = urllib.request.urlopen(url).read()
		soup = BeautifulSoup(html, "html.parser")
		if "no more stargazers" in soup.text or "Be the first to star" in soup.text:
			break
		print_stargazers(soup)


def get_repo_from_arguments():
	if len(sys.argv) != 2:
		raise Exception(
			"Please give exactly one argument: " +
			"A github repository (e.g. 'martanne/vis')."
		)
	return sys.argv[1]


def print_stargazers(soup):
	headers = soup.find_all('h3', class_='follow-list-name')
	for header in headers:
		print(header.find_all('a', href=True)[0]['href'][1:])


if __name__ == '__main__':
	main()
